CREATE TABLE ProductEntity (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(90) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);