CREATE TABLE Products (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  entity_id INTEGER NOT NULL,
  sold BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (entity_id) REFERENCES ProductEntity(id) ON DELETE CASCADE
);