CREATE TABLE Users (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  username VARCHAR(120) NOT NULL,
  email VARCHAR(155) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);